name: deno

env:
  DENO_VERSION: 1.x
  DENOPS_PATH: "./"

on:
  schedule:
    - cron: "0 7 * * 0"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Type check
        run: |
          deno test --unstable --no-run denops/**/*.ts

  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Lint
        run: deno lint denops

  format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Format
        run: |
          deno fmt --check denops

  #test:
  #  runs-on: ubuntu-20.04

  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: denoland/setup-deno@main
  #      with:
  #        deno-version: ${{ env.DENO_VERSION }}
  #    - name: Test
  #      run: |
  #        deno test --unstable -A
  #      timeout-minutes: 5
